##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: details
  namespace: consul
  labels:
    account: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: consul
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      serviceAccountName: details
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
